import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { AccessControl } from '../auth/access.js';
import { CaseGraphStorage } from '../case-graph/case-graph-storage.js';
import { CaseGraphService, GraphNotFoundError } from '../case-graph/case-graph-service.js';
import { GraphStateService } from '../case-graph/graph-state-service.js';
import { RelationGraphService, FieldError } from '../case-graph/relation-service.js';
import { CaseAuditStorage, AuditNotFoundError } from '../case-audit/storage.js';
import { CaseAuditService } from '../case-audit/service.js';
import { QueryClientNotConfiguredError } from '../case-graph/query-client.js';
type R=Record<string,any>;
export function registerBusinessRoutes(server:FastifyInstance,d:{access:AccessControl;graphs:CaseGraphStorage;graphService:CaseGraphService;graphState:GraphStateService;relations:RelationGraphService;audits:CaseAuditStorage;auditService:CaseAuditService}){
 const auth=(q:FastifyRequest)=>d.access.authorize(q);const body=(q:FastifyRequest)=>rec(q.body);
 server.post('/api/case-graph/graphs',async(q,r)=>{await auth(q);const p=body(q);try{const caseId=req(p.caseId,'caseId'),name=req(p.graphName,'graphName');if(!objects(p.tradeCards))return r.code(400).send({error:'tradeCards 必须是对象数组'});return d.graphService.createGraph(caseId,name,p.tradeCards);}catch(e){return mapped(r,e,'建图失败');}});
 server.get('/api/case-graph/graphs',async(q,r)=>{await auth(q);try{return{items:await d.graphService.listGraphs(text(rec(q.query).caseId))};}catch(e){return mapped(r,e,'图列表读取失败',502);}});
 server.get('/api/case-graph/cases',async(q,r)=>{await auth(q);try{return{items:await d.graphService.listCases()};}catch(e){return mapped(r,e,'案件列表读取失败',502);}});
 server.get<{Params:{case_id:string}}>('/api/case-graph/cases/:case_id/accounts',async(q,r)=>{await auth(q);try{return{items:await d.graphService.listAccounts(req(q.params.case_id,'case_id'),text(rec(q.query).keyword))};}catch(e){return mapped(r,e,'主体列表读取失败',502);}});
 server.get('/api/case-audit/cases',async(q,r)=>{await auth(q);try{return{items:await d.auditService.listCases()};}catch(e){return mapped(r,e,'案件列表读取失败',502);}});
 server.get<{Params:{case_id:string}}>('/api/case-audit/cases/:case_id/overview',async(q,r)=>{await auth(q);try{return await d.auditService.overview(req(q.params.case_id,'case_id'));}catch(e){return mapped(r,e,'案件审计概览读取失败',502);}});
 server.get<{Params:{case_id:string}}>('/api/case-audit/cases/:case_id/audits',async(q,r)=>{await auth(q);try{const c=req(q.params.case_id,'case_id'),ensure=['1','true','yes'].includes(text(rec(q.query).ensure)),active=ensure?await d.audits.getOrCreateDefault(c):null,items=await d.audits.listAudits(c);return{items,activeAuditId:text(active?.auditId||items[0]?.auditId)};}catch(e){return mapped(r,e,'审计档案读取失败');}});
 server.post('/api/case-audit/audits',async(q,r)=>{await auth(q);const p=body(q);try{return await d.audits.createAudit({caseId:req(p.caseId,'caseId'),auditName:text(p.auditName),conditions:rec(p.conditions),filters:rec(p.filters)});}catch(e){return mapped(r,e,'审计档案创建失败');}});
 server.post<{Params:{audit_id:string}}>('/api/case-audit/audits/:audit_id',async(q,r)=>{await auth(q);try{return await d.audits.updateAudit(req(q.params.audit_id,'audit_id'),body(q));}catch(e){return mapped(r,e,'审计档案保存失败');}});
 server.post('/api/case-audit/run',async(q,r)=>{await auth(q);const p=body(q);try{req(p.caseId,'caseId');const result=await d.auditService.runCaseAudit(p);if(text(p.auditId))await d.audits.saveRunResult(text(p.auditId),p,result);return result;}catch(e){return mapped(r,e,'涉诈资金审计失败',502);}});
 server.get<{Params:{graph_id:string}}>('/api/case-graph/graph/:graph_id',async(q,r)=>{await auth(q);try{const g=await d.graphs.getGraph(req(q.params.graph_id,'graph_id'));return g||r.code(404).send({error:'图不存在'});}catch(e){return mapped(r,e,'读取图失败');}});
 server.post<{Params:{graph_id:string}}>('/api/case-graph/graph/:graph_id',async(q,r)=>{await auth(q);try{const id=req(q.params.graph_id,'graph_id'),p=body(q),g=await d.graphService.updateGraph(id,p);if(text(g.caseId)&&(Object.hasOwn(p,'drillNums')||Object.hasOwn(p,'drillType')))try{await d.graphState.updateGraphSettings(g.caseId,id,Object.fromEntries(['drillNums','drillType'].filter(k=>k in p).map(k=>[k,p[k]])));}catch{}return g;}catch(e){return mapped(r,e,'更新图失败');}});
 server.delete<{Params:{graph_id:string}}>('/api/case-graph/graph/:graph_id',async(q,r)=>{await auth(q);try{return await d.graphService.deleteGraph(req(q.params.graph_id,'graph_id'))?{ok:true}:r.code(404).send({error:'图不存在'});}catch(e){return mapped(r,e,'删除图失败');}});
 const relation=(path:string,method:keyof RelationGraphService,label:string,validate?:(p:R)=>string|null)=>server.post(path,async(q,r)=>{await auth(q);const p=body(q),bad=validate?.(p);if(bad)return r.code(400).send({error:bad});try{return await (d.relations[method] as any).call(d.relations,p);}catch(e){return mapped(r,e,label,502);}});
 relation('/api/case-graph/relation/query','querySeedOneHop','关系图查询失败',p=>!objects(p.seeds)?'seeds 必须是对象数组':null);
 relation('/api/case-graph/relation/complete','completeCurrentGraph','图上节点关系分析失败',p=>!objects(p.accounts)?'accounts 必须是对象数组':null);
 relation('/api/case-graph/relation/filter','filterCurrentGraph','图筛选失败',p=>'filters'in p&&!isRec(p.filters)?'filters 必须是对象':null);
 relation('/api/case-graph/relation/exclude-trades','excludeTrades','交易核查失败');relation('/api/case-graph/relation/summary-candidates','querySummaryCandidates','线索候选读取失败');relation('/api/case-graph/relation/summary-selection','applySummarySelection','线索扩展失败');relation('/api/case-graph/relation/exclude-node','excludeNode','排除节点失败');relation('/api/case-graph/relation/restore-node','restoreNode','恢复节点失败');relation('/api/case-graph/relation/restore-nodes','restoreNodes','恢复节点失败');relation('/api/case-graph/relation/investigation-group','applyInvestigationGroup','研判组操作失败');relation('/api/case-graph/relation/manual-node','addManualNode','创建交易主体失败');relation('/api/case-graph/relation/manual-trade','addManualTrade','补充资金往来失败');relation('/api/case-graph/relation/reality-relation','addRealityRelation','标注现实关系失败');
 server.get<{Params:{case_id:string;graph_id:string}}>('/api/case-graph/relation/state/:case_id/:graph_id',async(q,r)=>{await auth(q);try{return await d.graphState.loadCurrent(req(q.params.case_id,'case_id'),req(q.params.graph_id,'graph_id'));}catch(e){return mapped(r,e,'图状态读取失败',404);}});
 server.get<{Params:{case_id:string;graph_id:string}}>('/api/case-graph/relation/state/:case_id/:graph_id/steps',async(q,r)=>{await auth(q);try{return{items:await d.graphState.listSteps(req(q.params.case_id,'case_id'),req(q.params.graph_id,'graph_id'))};}catch(e){return mapped(r,e,'图步骤读取失败',404);}});
 server.post<{Params:{case_id:string;graph_id:string}}>('/api/case-graph/relation/state/:case_id/:graph_id/operations/layout',async(q,r)=>{await auth(q);try{const p=body(q);if(!isRec(p.nodePositions))return r.code(400).send({error:'nodePositions 必须是对象'});return await d.graphState.updateLayout({caseId:req(q.params.case_id,'case_id'),graphId:req(q.params.graph_id,'graph_id'),graphName:text(p.graphName),nodePositions:p.nodePositions,positionMeta:rec(p.positionMeta),groupLayout:rec(p.groupLayout),viewport:rec(p.viewport)});}catch(e){return mapped(r,e,'图谱布局保存失败');}});
 server.post<{Params:{case_id:string;graph_id:string}}>('/api/case-graph/relation/state/:case_id/:graph_id/operations/latest-step-layout',async(q,r)=>{await auth(q);try{return await d.graphState.updateLatestStepLayout(req(q.params.case_id,'case_id'),req(q.params.graph_id,'graph_id'),body(q));}catch(e){return mapped(r,e,'步骤布局保存失败');}});
 server.post<{Params:{case_id:string;graph_id:string}}>('/api/case-graph/relation/state/:case_id/:graph_id/operations/node-note',async(q,r)=>{await auth(q);try{const p=body(q);return await d.graphState.updateNodeNote({caseId:req(q.params.case_id,'case_id'),graphId:req(q.params.graph_id,'graph_id'),graphName:text(p.graphName),nodeId:req(p.nodeId,'nodeId'),note:text(p.note),sourceNote:text(p.sourceNote)});}catch(e){return mapped(r,e,'主体备注保存失败');}});
 server.post('/api/case-graph/target-detail',async(q,r)=>{await auth(q);try{return await d.graphService.targetDetail(body(q));}catch(e){return mapped(r,e,'边明细加载失败',502);}});
 server.post('/api/case-graph/context',async(q,r)=>{await auth(q);try{const p=body(q);return await d.graphState.writeCurrentContext({caseId:req(p.caseId,'caseId'),graphId:req(p.graphId,'graphId'),graphName:text(p.graphName),chatId:text(p.chatId),focus:isRec(p.focus)?p.focus:null,latestStepId:text(p.latestStepId),latestOperation:rec(p.latestOperation),latestStepSummary:rec(p.latestStepSummary),deltaSummary:rec(p.deltaSummary)});}catch(e){return mapped(r,e,'更新图上下文失败');}});
}
function mapped(r:any,e:any,label:string,status=500){if(e instanceof QueryClientNotConfiguredError)return r.code(503).send({error:e.message});if(e instanceof AuditNotFoundError)return r.code(404).send({error:'审计档案不存在'});if(e instanceof GraphNotFoundError)return r.code(404).send({error:'图不存在'});if(e instanceof FieldError)return r.code(400).send({error:`缺少或无效的必要字段: ${e.field}`});if(e instanceof Error&&['caseId','graphId','graphName','tradeCards','auditId','audit_id','case_id','graph_id','victimCondition','sourceCondition'].includes(e.message))return r.code(400).send({error:`缺少或无效的必要字段: ${e.message}`});return r.code(status).send({error:`${label}: ${e instanceof Error?e.message:String(e)}`});}function text(v:any){return v==null?'':String(v).trim();}function req(v:any,k:string){const x=text(v);if(!x)throw new FieldError(k);return x;}function isRec(v:any):v is R{return!!v&&typeof v==='object'&&!Array.isArray(v);}function rec(v:any):R{return isRec(v)?v:{}}function objects(v:any):v is R[]{return Array.isArray(v)&&v.every(isRec);}
