import { Decimal } from 'decimal.js';
import type { CaseGraphQueryClient, JsonRecord as R } from '../case-graph/query-client.js';

const Z=new Decimal(0); const D='借',C='贷';
export class CaseAuditService {
  constructor(private readonly query:CaseGraphQueryClient){}
  listCases(){return this.query.listCases();}
  async overview(caseId:string){if(!text(caseId))throw new Error('caseId');const x=await this.query.caseAuditOverview(caseId);return{caseId:text(caseId),tradeCount:int(x.tradeCount),sourceFileCount:int(x.sourceFileCount),balanceMissingCount:int(x.balanceMissingCount),minTradeTime:text(x.minTradeTime),maxTradeTime:text(x.maxTradeTime),totalTradeAmount:money(dec(x.totalTradeAmount))};}
  async runCaseAudit(p:R):Promise<R>{
    const caseId=req(p.caseId,'caseId'),vc=list(p.victimCards??p.victims),vn=list(p.victimNames),sc=list(p.suspectCards??p.suspects),sn=list(p.suspectNames),sac=list(p.sourceAccountCards),san=list(p.sourceAccountNames),sa=dec(p.sourceAmount),sm=text(p.sourceMode),sl=text(p.sourceLabel);
    if(sm==='recognized'){if(!(sa?.gt(0)&&(sac.length||san.length)))throw new Error('sourceCondition');}else if(!vc.length&&!vn.length)throw new Error('victimCondition');
    const trades=(await this.query.queryCaseAuditTrades(p)).map(asTrade).sort(sortTrade); const {result,stats}=run(trades,vc,vn,sc,sn,sac,san,sm==='recognized'?sa:null,sl);
    const recognized=[...result.tradeMap.values()].map(serialize),auditTrades=trades.map(serialize),suspectResults=buildSuspects(result,recognized),graph=buildGraph(recognized,vc,vn,sc,sn),warnings=buildWarnings(stats,vc,vn,sc,sn,sm);
    return{schemaVersion:'case-audit.v1',caseId,scope:'case',algorithm:{id:'legacyFileAuditAlgorithm',source:'GaTradeServiceImpl.doAudit',inputMode:'caseTrades',rules:['贷方流水命中被害人后累计被害入账金额','上一层已认定金额可作为下一层账号的待判断资金池起点','借方流水未命中嫌疑人时按交易金额冲减累计入账','借方流水命中嫌疑人时用累计入账减转出后余额计算可认定金额']},summary:{tradeCount:trades.length,sourceFileCount:stats.source_file_count,accountGroupCount:stats.account_group_count,recognizedTradeCount:recognized.length,suspectCount:suspectResults.length,fraudAmount:money(result.fraudAmount),fraudAmountNumber:num(result.fraudAmount),confirmAmount:money(result.confirmAmount),confirmAmountNumber:num(result.confirmAmount),caseAmount:money(result.caseAmount),caseAmountNumber:num(result.caseAmount),balanceMissingCount:stats.balance_missing_count,unknownDirectionCount:stats.unknown_direction_count,missingGroupCardCount:stats.missing_group_card_count,victimInputCount:vc.length+vn.length,suspectInputCount:sc.length+sn.length,sourceInputCount:sac.length+san.length},quality:{warnings},suspectNames:result.suspectNames,suspectResults,reasoningSteps:result.reasoning,graph,trades:auditTrades};
  }
}
type Trade=R&{tradeAmount:Decimal,payerTradeBalance:Decimal|null,tradeBalance:Decimal|null};
type Result={confirmAmount:Decimal,fraudAmount:Decimal,caseAmount:Decimal,suspectNames:string[],tradeMap:Map<string,Trade>,events:R[],reasoning:R[]};
type Info={payeeTrades:Trade[],suspectNames:string[],stepIds:string[],victimAmount:Decimal,faultAmount:Decimal,confirmAmount:Decimal,caseAmount:Decimal,sourceAmount:Decimal};
const info=():Info=>({payeeTrades:[],suspectNames:[],stepIds:[],victimAmount:Z,faultAmount:Z,confirmAmount:Z,caseAmount:Z,sourceAmount:Z});
function run(trades:Trade[],vc:string[],vn:string[],sc:string[],sn:string[],sac:string[],san:string[],sa:Decimal|null,sl:string){const groups=new Map<string,Trade[]>(),files=new Set<string>();let unknown=0,missing=0,balanceMissing=0;for(const t of trades){if(t.fileId)files.add(t.fileId);const key=t.jdFlag===D?t.payerTradeCard:t.jdFlag===C?t.payeeTradeCard:'';if(!key){t.jdFlag===D||t.jdFlag===C?missing++:unknown++;continue;}const a=groups.get(key)||[];a.push(t);groups.set(key,a);}const result:Result={confirmAmount:Z,fraudAmount:Z,caseAmount:Z,suspectNames:[],tradeMap:new Map(),events:[],reasoning:[]};let ix=0;
 for(const [card,base] of groups){let i=info();if(sa?.gt(0)&&isSource(card,base,sac,san)){const id=`reason:${card}:source:${++ix}`;i.victimAmount=sa;i.sourceAmount=sa;i.stepIds.push(id);result.reasoning.push(sourceStep(id,card,accountName(card,base),sa,sl,base[0]));}
  for(const t of base){const amount=t.tradeAmount;if(t.jdFlag===C){if((vc.length||vn.length)&&isVictim(t,vc,vn)){const id=`reason:${card}:${++ix}`,before=i.victimAmount;i.payeeTrades.push(t);i.victimAmount=i.victimAmount.add(amount);i.stepIds.push(id);result.reasoning.push(step(id,'victim_credit',t,card,before,i.victimAmount));}continue;}if(t.jdFlag!==D)continue;
   if(!isSuspect(t,sc,sn)){const id=`reason:${card}:${++ix}`,before=i.victimAmount,last=i.victimAmount.sub(amount);if(last.gt(0)){i.victimAmount=last;i.stepIds.push(id);result.reasoning.push(step(id,'worst_case_offset',t,card,before,last));i.payeeTrades=[];}else{if(i.victimAmount.gt(0)){const ids=[...i.stepIds,id];result.reasoning.push({...step(id,'worst_case_clear',t,card,before,Z),segmentStepIds:ids});}i=info();}continue;}
   t.caseAmount=amount;t.flowStatus='suspect_outflow';t.flowStatusText='嫌疑人收款，计算最低可认定';i.caseAmount=i.caseAmount.add(amount);const bal=t.payerTradeBalance;if(!bal){balanceMissing++;continue;}const confirm=i.victimAmount.sub(bal);if(confirm.lte(0)){const id=`reason:${card}:${++ix}`;i.stepIds.push(id);result.reasoning.push(step(id,'suspect_no_confirm',t,card,i.victimAmount,i.victimAmount,confirm));continue;}
   const id=`reason:${card}:${++ix}`,segment=[...i.stepIds,id];result.reasoning.push({...step(id,'suspect_recognition',t,card,i.victimAmount,confirm,confirm),segmentStepIds:segment});t.confirmAmount=confirm;i.confirmAmount=i.confirmAmount.add(confirm);if(t.payeeAccountName)i.suspectNames.push(t.payeeAccountName);const related:string[]=[],yes:string[]=[],no:string[]=[];for(const pt of i.payeeTrades){pt.relationId=tid(t);if(pt.tradeAmount.gt(bal)){pt.flowStatus='confirmed_flow';pt.flowStatusText='余额无法完全包含，可标识具体流向';yes.push(tid(pt));}else{pt.flowStatus='balance_excluded';pt.flowStatusText='余额可包含，应排除具体流向';no.push(tid(pt));}pt.faultAmount=pt.tradeAmount;i.faultAmount=i.faultAmount.add(pt.tradeAmount);if(!result.tradeMap.has(tid(t)))result.tradeMap.set(tid(t),t);related.push(tid(pt));}
   result.events.push({tradeId:tid(t),suspectName:t.payeeAccountName,suspectCard:t.payeeTradeCard,confirmAmount:confirm,caseAmount:amount,faultAmount:i.faultAmount,sourceAmount:i.sourceAmount,relatedTradeIds:related,confirmedRelatedTradeIds:yes,balanceExcludedTradeIds:no,reasoningStepIds:segment});result.fraudAmount=result.fraudAmount.add(i.faultAmount.gt(0)?i.faultAmount:i.sourceAmount);result.confirmAmount=result.confirmAmount.add(i.confirmAmount);result.caseAmount=result.caseAmount.add(i.caseAmount);for(const n of i.suspectNames)if(n&&!result.suspectNames.includes(n))result.suspectNames.push(n);for(const pt of i.payeeTrades)if(pt.relationId)result.tradeMap.set(tid(pt),pt);i=info();
  }
 }
 return{result,stats:{source_file_count:files.size,account_group_count:groups.size,unknown_direction_count:unknown,missing_group_card_count:missing,balance_missing_count:balanceMissing}};
}
function asTrade(r:R):Trade{const a=dec(r.trade_amount??r.tradeAmount)||Z,pb=dec(r.payer_trade_balance??r.payerTradeBalance),tb=dec(r.trade_balance??r.tradeBalance),row=text(r.row_id??r.tradeRowId);return{id:text(r.id)||row,tradeRowId:row,fileId:text(r.file_id??r.fileId),fileName:text(r.file_name??r.fileName),serialNumber:text(r.serial_number??r.serialNumber),tradeAmount:a,tradeAmountText:money(a),tradeTime:text(r.trade_time??r.tradeTime),jdFlag:text(r.jd_flag??r.jdFlag),payerSuspectId:text(r.payer_suspect_id??r.payerSuspectId),payerAccountId:text(r.payer_account_id??r.payerAccountId),payerAccountName:text(r.payer_account_name??r.payerAccountName),payerTradeCard:text(r.payer_trade_card??r.payerTradeCard),payerTradeBalance:pb,payeeSuspectId:text(r.payee_suspect_id??r.payeeSuspectId),payeeAccountId:text(r.payee_account_id??r.payeeAccountId),payeeAccountName:text(r.payee_account_name??r.payeeAccountName),payeeTradeCard:text(r.payee_trade_card??r.payeeTradeCard),tradeBalance:tb,relationId:'',flowStatus:'',flowStatusText:'',faultAmount:null,confirmAmount:null,caseAmount:null};}
function step(id:string,kind:string,t:Trade,card:string,before:Decimal,after:Decimal,confirm:Decimal|null=null):R{return{id,kind,tradeId:tid(t),serialNumber:text(t.serialNumber),tradeTime:text(t.tradeTime),accountCard:text(card),payerName:text(t.payerAccountName),payerCard:text(t.payerTradeCard),payeeName:text(t.payeeAccountName),payeeCard:text(t.payeeTradeCard),amount:money(t.tradeAmount),amountNumber:num(t.tradeAmount),poolBefore:money(before),poolBeforeNumber:num(before),poolAfter:money(after),poolAfterNumber:num(after),payerTradeBalance:money(t.payerTradeBalance),payerTradeBalanceNumber:num(t.payerTradeBalance),confirmAmount:money(confirm),confirmAmountNumber:num(confirm),fileName:text(t.fileName||t.fileId)};}
function sourceStep(id:string,card:string,name:string,amount:Decimal,label:string,t?:Trade):R{return{id,kind:'source_carryover',tradeId:id,serialNumber:'上一层认定',tradeTime:text(t?.tradeTime),accountCard:text(card),payerName:text(label)||'上一层认定金额',payerCard:'',payeeName:text(name),payeeCard:text(card),amount:money(amount),amountNumber:num(amount),poolBefore:'0.00',poolBeforeNumber:0,poolAfter:money(amount),poolAfterNumber:num(amount),payerTradeBalance:'0.00',payerTradeBalanceNumber:0,confirmAmount:'0.00',confirmAmountNumber:0,fileName:'上一层审计结果'};}
function serialize(t:Trade):R{const keys=['id','tradeRowId','fileId','fileName','serialNumber','tradeTime','jdFlag','payerSuspectId','payerAccountId','payerAccountName','payerTradeCard','payeeSuspectId','payeeAccountId','payeeAccountName','payeeTradeCard','relationId','flowStatus','flowStatusText'];const o=Object.fromEntries(keys.map(k=>[k,t[k]]));for(const k of ['tradeAmount','payerTradeBalance','tradeBalance','faultAmount','confirmAmount','caseAmount']){o[k]=money(t[k]);o[`${k}Number`]=num(t[k]);}return o;}
function buildSuspects(r:Result,trades:R[]):R[]{const faults=new Map<string,Decimal>();for(const t of trades)if(text(t.relationId))faults.set(text(t.relationId),(faults.get(text(t.relationId))||Z).add(dec(t.faultAmount)||Z));const map=new Map<string,R>();for(const e of r.events){const n=text(e.suspectName)||text(e.suspectCard)||'未知嫌疑人',x=map.get(n)||{suspectName:n,suspectCard:text(e.suspectCard),confirmAmount:Z,caseAmount:Z,fraudAmount:Z,tradeIds:[],relatedTradeIds:[],confirmedRelatedTradeIds:[],balanceExcludedTradeIds:[],reasoningStepIds:[]},id=text(e.tradeId);x.confirmAmount=x.confirmAmount.add(e.confirmAmount||Z);x.caseAmount=x.caseAmount.add(e.caseAmount||Z);x.fraudAmount=x.fraudAmount.add(faults.get(id)||e.sourceAmount||Z);if(id)x.tradeIds.push(id);for(const k of ['relatedTradeIds','confirmedRelatedTradeIds','balanceExcludedTradeIds','reasoningStepIds'])x[k].push(...(e[k]||[]));map.set(n,x);}return[...map.values()].sort((a,b)=>b.confirmAmount.cmp(a.confirmAmount)).map(x=>({suspectName:x.suspectName,suspectCard:x.suspectCard,confirmAmount:money(x.confirmAmount),confirmAmountNumber:num(x.confirmAmount),caseAmount:money(x.caseAmount),caseAmountNumber:num(x.caseAmount),fraudAmount:money(x.fraudAmount),fraudAmountNumber:num(x.fraudAmount),tradeIds:uniq(x.tradeIds),relatedTradeIds:uniq(x.relatedTradeIds),confirmedRelatedTradeIds:uniq(x.confirmedRelatedTradeIds),balanceExcludedTradeIds:uniq(x.balanceExcludedTradeIds),reasoningStepIds:uniq(x.reasoningStepIds)}));}
function buildGraph(ts:R[],vc:string[],vn:string[],sc:string[],sn:string[]):R{const nodes=new Map<string,R>(),edges:R[]=[];for(const t of ts){const pk=t.payerAccountId||t.payerTradeCard||t.payerAccountName||`payer:${t.id}`,qk=t.payeeAccountId||t.payeeTradeCard||t.payeeAccountName||`payee:${t.id}`,p=`account:${pk}`,q=`account:${qk}`;nodes.set(p,nodes.get(p)||{id:p,label:t.payerAccountName||t.payerTradeCard||'未知主体',card:text(t.payerTradeCard),role:(!vc.length&&!vn.length||vc.includes(t.payerTradeCard)||vn.includes(t.payerAccountName))?'victim':'transfer'});nodes.set(q,nodes.get(q)||{id:q,label:t.payeeAccountName||t.payeeTradeCard||'未知主体',card:text(t.payeeTradeCard),role:(!sc.length&&!sn.length||sc.includes(t.payeeTradeCard)||sn.includes(t.payeeAccountName))?'suspect':'transfer'});edges.push({id:`audit:${t.id}`,source:p,target:q,tradeId:t.id,amount:t.tradeAmount||'0.00',amountNumber:t.tradeAmountNumber||0,confirmAmount:t.confirmAmount||'0.00',confirmAmountNumber:t.confirmAmountNumber||0,flowStatus:t.flowStatus||'',flowStatusText:t.flowStatusText||'',fileName:t.fileName||''});}return{nodes:[...nodes.values()],edges};}
function buildWarnings(s:R,vc:string[],vn:string[],sc:string[],sn:string[],mode:string):string[]{const w:string[]=[];if(mode==='recognized')w.push('本轮以上一层已认定金额作为资金池起点，继续按原版规则追踪该账号向下级转出的最低可认定金额。');else if(!vc.length&&!vn.length)w.push('缺少被害人条件，涉诈资金审计需要以被害人入账作为追踪起点。');if(!sc.length&&!sn.length)w.push('未限定嫌疑人条件，本次按发现模式从被害人资金链的出账端识别候选嫌疑人，最终认定需由办案人员核验。');if(s.balance_missing_count)w.push(`有 ${s.balance_missing_count} 笔嫌疑人出账缺少转出后余额，原版算法无法计算可认定金额，已按原规则跳过。`);if(s.unknown_direction_count)w.push(`有 ${s.unknown_direction_count} 笔流水的借贷标识不是“借/贷”，未进入原版审计分组。`);if(s.missing_group_card_count)w.push(`有 ${s.missing_group_card_count} 笔流水缺少用于分组的交易账号，未进入原版审计分组。`);return w;}
function isVictim(t:Trade,c:string[],n:string[]){return(!c.length&&!n.length)||c.includes(t.payerTradeCard)||n.includes(t.payerAccountName);}function isSuspect(t:Trade,c:string[],n:string[]){return(!c.length&&!n.length)||c.includes(t.payeeTradeCard)||n.includes(t.payeeAccountName);}function isSource(card:string,ts:Trade[],c:string[],n:string[]){return c.includes(card)||ts.some(t=>(t.payerTradeCard===card&&n.includes(t.payerAccountName))||(t.payeeTradeCard===card&&n.includes(t.payeeAccountName)));}function accountName(card:string,ts:Trade[]){for(const t of ts){if(t.payerTradeCard===card&&t.payerAccountName)return t.payerAccountName;if(t.payeeTradeCard===card&&t.payeeAccountName)return t.payeeAccountName;}return card;}
function sortTrade(a:Trade,b:Trade){return text(a.tradeTime).localeCompare(text(b.tradeTime))||(parseInt(a.serialNumber)||0)-(parseInt(b.serialNumber)||0)||text(a.tradeRowId).localeCompare(text(b.tradeRowId))||tid(a).localeCompare(tid(b));}function tid(t:R){return text(t.id||t.tradeRowId);}function dec(v:any):Decimal|null{if(v==null||v==='')return null;try{return new Decimal(String(v).replaceAll(',',''));}catch{return null;}}function money(v:any){return (v instanceof Decimal?v:dec(v)||Z).toDecimalPlaces(2,Decimal.ROUND_HALF_UP).toFixed(2);}function num(v:any){return Number(money(v));}function int(v:any){return Number.parseInt(String(v||0))||0;}function text(v:any){return v==null?'':String(v).trim();}function req(v:any,k:string){const x=text(v);if(!x)throw new Error(k);return x;}function list(v:any){const a=typeof v==='string'?v.replaceAll('，',',').replaceAll('\n',',').split(','):Array.isArray(v)?v:[];return uniq(a.map(text).filter(Boolean));}function uniq<T>(v:T[]):T[]{return[...new Set(v)];}
